version: '2'
services:
  Web:
    image: getarunkumarbabu/arunimages
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  redis:
    image: redis
